import type {Metadata} from 'next'
import './globals.css'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-poppins'>
      <body>{children}</body>
    </html>
  )
}
