import type {Metadata} from 'next'
import './globals.css'
import ItineraryPage from './pages/itineraryPage/page'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='font-poppins'>
      <body>
        {children}
      </body>
    </html>
  )
}
